name: cherry
description: Simple yet powerful, open-source SpaceX launch tracker.

version: 2.11.1+70

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  add_2_calendar: ^1.4.0
  big_tip: ^1.1.1
  cherry_components: ^0.0.1+4
  dio: ^3.0.10
  expand_widget: ^1.1.0
  equatable: ^1.2.5
  flutter_i18n: ^0.20.0
  flutter_local_notifications: ^2.0.0+1
  flutter_map: ^0.10.1+1
  flutter_markdown: ^0.4.4
  flutter_native_timezone: ^1.0.4
  flutter_swiper: ^1.1.6
  flutter_web_browser: ^0.12.0
  google_fonts: ^1.1.0
  intl: ^0.16.1
  in_app_review: ^0.2.01
  lint: ^1.2.0
  package_info: ^0.4.3
  provider: ^4.3.2+2
  quick_actions: ^0.4.0+9
  row_collection: ^0.2.4
  search_page: ^1.3.0
  share: ^0.6.5+2
  shared_preferences: ^0.5.12
  sliver_fab: ^1.0.0
  system_setting: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.1.9
  flutter_launcher_name: ^0.0.1

flutter_icons:
  image_path: assets/icons/icon_app.png
  android: true
  ios: true

flutter_native_splash:
  image: assets/icons/icon_splash.jpg
  color: "#151515"

flutter_launcher_name:
  name: "AlmanacX"

flutter:
  assets:
    - assets/flutter_i18n/
    - assets/icons/

  uses-material-design: true
